Getting Started:
- Getting Started.md
markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
    auto_title: true
    line_spans: __span
    linenums_style: pymdownx-inline
    pygments_lang_class: true
    use_pygments: true
- pymdownx.superfences
- pymdownx.inlinehilite
nav:
- API:
  - dummy_files:
    - hw: dummy_files/hw.md
  - __init__: __init__.md
  - themes: themes.md
  - mkdocs: mkdocs.md
  - llm: llm.md
  - cli: cli.md
  - core: core.md
- Getting Started: Getting Started.md
site_name: Meowdoc
theme:
  name: material
  palette:
    primary: black
    scheme: slate
