nav:
- Home: index.md
- API:
  - __init__: __init__.md
  - core: core.md
  - mkdocs: mkdocs.md
  - themes: themes.md
  - cli: cli.md
  - llm: llm.md
  - dummy_files:
    - hw: dummy_files/hw.md
site_name: Meowdoc
theme:
  name: material
