!!python/object/apply:collections.OrderedDict
- - - markdown_extensions
    - - !!python/object/apply:collections.OrderedDict
        - - - pymdownx.highlight
            - !!python/object/apply:collections.OrderedDict
              - - - anchor_linenums
                  - true
                - - auto_title
                  - true
                - - line_spans
                  - __span
                - - linenums_style
                  - pymdownx-inline
                - - pygments_lang_class
                  - true
                - - use_pygments
                  - true
      - pymdownx.superfences
      - pymdownx.inlinehilite
  - - nav
    - - !!python/object/apply:collections.OrderedDict
        - - - Home
            - index.md
      - !!python/object/apply:collections.OrderedDict
        - - - API
            - - !!python/object/apply:collections.OrderedDict
                - - - __init__
                    - __init__.md
              - !!python/object/apply:collections.OrderedDict
                - - - core
                    - core.md
              - !!python/object/apply:collections.OrderedDict
                - - - mkdocs
                    - mkdocs.md
              - !!python/object/apply:collections.OrderedDict
                - - - themes
                    - themes.md
              - !!python/object/apply:collections.OrderedDict
                - - - cli
                    - cli.md
              - !!python/object/apply:collections.OrderedDict
                - - - llm
                    - llm.md
              - !!python/object/apply:collections.OrderedDict
                - - - dummy_files
                    - - !!python/object/apply:collections.OrderedDict
                        - - - hw
                            - dummy_files/hw.md
              - !!python/object/apply:collections.OrderedDict
                - - - mkdocs
                    - mkdocs.md
              - !!python/object/apply:collections.OrderedDict
                - - - core
                    - core.md
              - !!python/object/apply:collections.OrderedDict
                - - - __init__
                    - __init__.md
              - !!python/object/apply:collections.OrderedDict
                - - - themes
                    - themes.md
              - !!python/object/apply:collections.OrderedDict
                - - - cli
                    - cli.md
              - !!python/object/apply:collections.OrderedDict
                - - - llm
                    - llm.md
              - !!python/object/apply:collections.OrderedDict
                - - - dummy_files
                    - - !!python/object/apply:collections.OrderedDict
                        - - - hw
                            - dummy_files/hw.md
              - !!python/object/apply:collections.OrderedDict
                - - - mkdocs
                    - mkdocs.md
              - !!python/object/apply:collections.OrderedDict
                - - - core
                    - core.md
              - !!python/object/apply:collections.OrderedDict
                - - - __init__
                    - __init__.md
              - !!python/object/apply:collections.OrderedDict
                - - - themes
                    - themes.md
              - !!python/object/apply:collections.OrderedDict
                - - - cli
                    - cli.md
              - !!python/object/apply:collections.OrderedDict
                - - - llm
                    - llm.md
              - !!python/object/apply:collections.OrderedDict
                - - - dummy_files
                    - - !!python/object/apply:collections.OrderedDict
                        - - - hw
                            - dummy_files/hw.md
              - !!python/object/apply:collections.OrderedDict
                - - - dummy_files
                    - - !!python/object/apply:collections.OrderedDict
                        - - - hw
                            - dummy_files/hw.md
              - !!python/object/apply:collections.OrderedDict
                - - - themes
                    - themes.md
              - !!python/object/apply:collections.OrderedDict
                - - - __init__
                    - __init__.md
              - !!python/object/apply:collections.OrderedDict
                - - - mkdocs
                    - mkdocs.md
              - !!python/object/apply:collections.OrderedDict
                - - - llm
                    - llm.md
              - !!python/object/apply:collections.OrderedDict
                - - - core
                    - core.md
              - !!python/object/apply:collections.OrderedDict
                - - - cli
                    - cli.md
              - !!python/object/apply:collections.OrderedDict
                - - - __init__
                    - __init__.md
              - !!python/object/apply:collections.OrderedDict
                - - - themes
                    - themes.md
              - !!python/object/apply:collections.OrderedDict
                - - - dummy_files
                    - - !!python/object/apply:collections.OrderedDict
                        - - - hw
                            - dummy_files/hw.md
              - !!python/object/apply:collections.OrderedDict
                - - - llm
                    - llm.md
              - !!python/object/apply:collections.OrderedDict
                - - - mkdocs
                    - mkdocs.md
              - !!python/object/apply:collections.OrderedDict
                - - - core
                    - core.md
              - !!python/object/apply:collections.OrderedDict
                - - - cli
                    - cli.md
              - !!python/object/apply:collections.OrderedDict
                - - - __init__
                    - __init__.md
              - !!python/object/apply:collections.OrderedDict
                - - - themes
                    - themes.md
              - !!python/object/apply:collections.OrderedDict
                - - - dummy_files
                    - - !!python/object/apply:collections.OrderedDict
                        - - - hw
                            - dummy_files/hw.md
              - !!python/object/apply:collections.OrderedDict
                - - - mkdocs
                    - mkdocs.md
              - !!python/object/apply:collections.OrderedDict
                - - - cli
                    - cli.md
              - !!python/object/apply:collections.OrderedDict
                - - - llm
                    - llm.md
              - !!python/object/apply:collections.OrderedDict
                - - - core
                    - core.md
              - !!python/object/apply:collections.OrderedDict
                - - - dummy_files
                    - - !!python/object/apply:collections.OrderedDict
                        - - - hw
                            - dummy_files/hw.md
              - !!python/object/apply:collections.OrderedDict
                - - - __init__
                    - __init__.md
              - !!python/object/apply:collections.OrderedDict
                - - - themes
                    - themes.md
              - !!python/object/apply:collections.OrderedDict
                - - - core
                    - core.md
              - !!python/object/apply:collections.OrderedDict
                - - - llm
                    - llm.md
              - !!python/object/apply:collections.OrderedDict
                - - - mkdocs
                    - mkdocs.md
              - !!python/object/apply:collections.OrderedDict
                - - - cli
                    - cli.md
  - - site_name
    - Meowdoc
  - - theme
    - !!python/object/apply:collections.OrderedDict
      - - - name
          - material
        - - palette
          - !!python/object/apply:collections.OrderedDict
            - - - primary
                - black
              - - scheme
                - slate
